### ISSUE TITLE
Suggest: add reference

### ISSUE THREAD

**Issue by richelbilderbeek** [KorfLab/Genesmith#1]
Dear Genesmith maintainer,

When I am at a GitHub repo of an academic software tool, I would expect a reference to the academic literature to read about Genesmith [1]. 

I suggest you add it to the README.md file. Sure, I can create a Pull Request to do so :+1:

Cheers, Richel Bilderbeek, postdoc

 * [1] Dandekar, Ravi. Genesmith: Implementing Customized Gene Finding To Assess The Landscape Of Genome Annotation. University of California, Davis, 2016.

**Comment by iankorf** [comment]
Development on that has really halted. There's something new under development.

**Comment by richelbilderbeek** [comment]
Ooh, exciting! If you need a volunteer to test things out, I may be one, if it's about gene prediction in viruses :rainbow: 

Well, I close this Issue then :+1:
